services:
  app:
    container_name: nestjs_app1
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cmp1611_db?schema=public

  db:
    container_name: postgres_db1
    image: postgres:13
    restart: always
    ports:
      - "5556:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmp1611_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
